global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "email-threat-api"

    metrics_path: "/metrics"

    static_configs:

      - targets:

          - email-threat-intelligence-platform-production.up.railway.app